---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: baalajimaestro/android_build:latest
  commands:
  - bash build.sh
